export const movieStarsData = [
  {
    id: 1,
    name: "Leonardo DiCaprio",
    img: "https://cdn.britannica.com/65/227665-050-D74A477E/American-actor-Leonardo-DiCaprio-2016.jpg",
    movies: ["Titanic", "Inception", "The Revenant", "The Wolf of Wall Street"],
    awards: ["1 Academy Award", "3 Golden Globes", "1 BAFTA"],
    profile: "https://www.imdb.com/name/nm0000138/",
  },
  {
    id: 2,
    name: "Meryl Streep",
    img: "https://people.com/thmb/mbTJLRoSjsx-YqMHOdxde6GWGfI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(858x0:860x2)/gettyimages-488082797-1408800336704602955627e16fd388c7.jpg",
    movies: [
      "The Devil Wears Prada",
      "Sophie's Choice",
      "Mamma Mia!",
      "The Iron Lady",
    ],
    awards: ["3 Academy Awards", "9 Golden Globes", "3 BAFTAs"],
    profile: "https://www.imdb.com/name/nm0000658/",
  },
  {
    id: 3,
    name: "Robert De Niro",
    img: "https://m.media-amazon.com/images/M/MV5BMjAwNDU3MzcyOV5BMl5BanBnXkFtZTcwMjc0MTIxMw@@._V1_FMjpg_UX1000_.jpg",
    movies: ["Taxi Driver", "Goodfellas", "Raging Bull", "The Irishman"],
    awards: ["2 Academy Awards", "1 Golden Globe", "1 BAFTA"],
    profile: "https://www.imdb.com/name/nm0000134/",
  },
  {
    id: 4,
    name: "Angelina Jolie",
    img: "https://breakthroughdxb.com/upload/iblock/7ef/c5fa0434f93ad9cabd796a209a595791.jpg",
    movies: ["Mr. & Mrs. Smith", "Maleficent", "Tomb Raider", "Changeling"],
    awards: [
      "1 Academy Award",
      "3 Golden Globes",
      "2 Screen Actors Guild Awards",
    ],
    profile: "https://www.imdb.com/name/nm0001401/",
  },
  {
    id: 5,
    name: "Brad Pitt",
    img: "https://m.media-amazon.com/images/M/MV5BMjA1MjE2MTQ2MV5BMl5BanBnXkFtZTcwMjE5MDY0Nw@@._V1_.jpg",
    movies: [
      "Fight Club",
      "Once Upon a Time in Hollywood",
      "Seven",
      "Inglourious Basterds",
    ],
    awards: ["2 Academy Awards", "2 Golden Globes", "1 BAFTA"],
    profile: "https://www.imdb.com/name/nm0000093/",
  },
  {
    id: 6,
    name: "Tom Hanks",
    img: "https://media.gettyimages.com/id/1724675/photo/american-actor-tom-hanks-holds-up-the-oscar-statuette-he-won-for-best-actor-for-his-role-in-the.jpg?s=612x612&w=gi&k=20&c=Gz0NzyEwGPGT87GPRfaSI-Yw6Iz2L53gus3PRuSI-Vo=",
    movies: [
      "Forrest Gump",
      "Saving Private Ryan",
      "Cast Away",
      "The Terminal",
    ],
    awards: ["2 Academy Awards", "4 Golden Globes", "7 Primetime Emmy Awards"],
    profile: "https://www.imdb.com/name/nm0000158/",
  },
  {
    id: 7,
    name: "Scarlett Johansson",
    img: "https://m.media-amazon.com/images/M/MV5BMTM3OTUwMDYwNl5BMl5BanBnXkFtZTcwNTUyNzc3Nw@@._V1_.jpg",
    movies: ["Lost in Translation", "The Avengers", "Marriage Story", "Lucy"],
    awards: ["1 BAFTA", "5 Golden Globe Nominations", "Tony Award"],
    profile: "https://www.imdb.com/name/nm0424060/",
  },
  {
    id: 8,
    name: "Johnny Depp",
    img: "https://m.media-amazon.com/images/M/MV5BZjA3NzZiZDktZjc2My00MzY2LThhOWMtZGFjYzg4ZDI2ZWVmXkEyXkFqcGc@._V1_.jpg",
    movies: [
      "Pirates of the Caribbean",
      "Edward Scissorhands",
      "Sweeney Todd",
      "Fantastic Beasts",
    ],
    awards: [
      "3 Academy Award Nominations",
      "1 Golden Globe",
      "Screen Actors Guild Award",
    ],
    profile: "https://www.imdb.com/name/nm0000136/",
  },
  {
    id: 9,
    name: "Cate Blanchett",
    img: "https://m.media-amazon.com/images/M/MV5BMTc1MDI0MDg1NV5BMl5BanBnXkFtZTgwMDM3OTAzMTE@._V1_.jpg",
    movies: [
      "The Lord of the Rings",
      "Blue Jasmine",
      "Carol",
      "Thor: Ragnarok",
    ],
    awards: ["2 Academy Awards", "3 Golden Globes", "3 BAFTAs"],
    profile: "https://www.imdb.com/name/nm0000949/",
  },
  {
    id: 10,
    name: "Denzel Washington",
    img: "https://upload.wikimedia.org/wikipedia/commons/4/40/Denzel_Washington_2018.jpg",
    movies: ["Training Day", "Malcolm X", "Fences", "The Equalizer"],
    awards: ["2 Academy Awards", "3 Golden Globes", "1 Tony Award"],
    profile: "https://www.imdb.com/name/nm0000243/",
  },
  {
    id: 11,
    name: "Julia Roberts",
    img: "https://cdn.britannica.com/01/236601-050-2CFDF711/Julia-Roberts-2019.jpg",
    movies: [
      "Pretty Woman",
      "Erin Brockovich",
      "Notting Hill",
      "Ocean's Eleven",
    ],
    awards: ["1 Academy Award", "3 Golden Globes"],
    profile: "https://www.imdb.com/name/nm0000210/",
  },
  {
    id: 12,
    name: "Christian Bale",
    img: "https://m.media-amazon.com/images/M/MV5BMTkxMzk4MjQ4MF5BMl5BanBnXkFtZTcwMzExODQxOA@@._V1_.jpg",
    movies: [
      "The Dark Knight",
      "American Psycho",
      "The Fighter",
      "Ford v Ferrari",
    ],
    awards: ["1 Academy Award", "2 Golden Globes"],
    profile: "https://www.imdb.com/name/nm0000288/",
  },
  {
    id: 13,
    name: "Natalie Portman",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXd3MSJo-GtYdptUlX0lCXIYKELiGMTVFD6w&s",
    movies: ["Black Swan", "V for Vendetta", "Jackie", "Thor"],
    awards: ["1 Academy Award", "2 Golden Globes"],
    profile: "https://www.imdb.com/name/nm0000204/",
  },
  {
    id: 14,
    name: "Tom Cruise",
    img: "https://images.mubicdn.net/images/cast_member/2184/cache-2992-1547409411/image-w856.jpg",
    movies: ["Top Gun", "Mission: Impossible", "Jerry Maguire", "Rain Man"],
    awards: ["3 Golden Globes", "3 Academy Award Nominations"],
    profile: "https://www.imdb.com/name/nm0000129/",
  },
  {
    id: 15,
    name: "Emma Watson",
    img: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Emma_Watson_2013.jpg",
    movies: [
      "Harry Potter",
      "Beauty and the Beast",
      "The Perks of Being a Wallflower",
    ],
    awards: ["1 Teen Choice Award", "MTV Movie Award"],
    profile: "https://www.imdb.com/name/nm0914612/",
  },
  {
    id: 16,
    name: "Hugh Jackman",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrF76vHu4Az1S6SrHvnFrxP4M_zsWoUSNcMQ&s",
    movies: ["Logan", "The Greatest Showman", "Les Misérables", "Wolverine"],
    awards: ["1 Golden Globe", "1 Tony Award"],
    profile: "https://www.imdb.com/name/nm0413168/",
  },
  {
    id: 17,
    name: "Jennifer Lawrence",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSnBMtsk7BmmLtg5BiNz_fa4Q1Na10et2Nvg&s",
    movies: ["The Hunger Games", "Silver Linings Playbook", "Joy", "X-Men"],
    awards: ["1 Academy Award", "3 Golden Globes"],
    profile: "https://www.imdb.com/name/nm2225369/",
  },
  {
    id: 18,
    name: "Ryan Gosling",
    img: "https://m.media-amazon.com/images/M/MV5BMTQzMjkwNTQ2OF5BMl5BanBnXkFtZTgwNTQ4MTQ4MTE@._V1_.jpg",
    movies: ["La La Land", "Drive", "Blade Runner 2049", "The Notebook"],
    awards: ["1 Golden Globe", "2 Academy Award Nominations"],
    profile: "https://www.imdb.com/name/nm0331516/",
  },
  {
    id: 19,
    name: "Morgan Freeman",
    img: "https://m.media-amazon.com/images/M/MV5BMTc0MDMyMzI2OF5BMl5BanBnXkFtZTcwMzM2OTk1MQ@@._V1_FMjpg_UX1000_.jpg",
    movies: ["The Shawshank Redemption", "Se7en", "Invictus", "Bruce Almighty"],
    awards: ["1 Academy Award", "1 Golden Globe"],
    profile: "https://www.imdb.com/name/nm0000151/",
  },
  {
    id: 20,
    name: "Keanu Reeves",
    img: "https://m.media-amazon.com/images/M/MV5BNDEzOTdhNDUtY2EyMy00YTNmLWE5MjItZmRjMmQzYTRlMGRkXkEyXkFqcGc@._V1_.jpg",
    movies: [
      "The Matrix",
      "John Wick",
      "Speed",
      "Bill & Ted's Excellent Adventure",
    ],
    awards: ["MTV Movie Award", "Teen Choice Award"],
    profile: "https://www.imdb.com/name/nm0000206/",
  },
  // {
  //   id: 21,
  //   name: "Charlize Theron",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/6/68/Charlize_Theron_Cannes_2015_2.jpg",
  //   movies: [
  //     "Mad Max: Fury Road",
  //     "Monster",
  //     "Atomic Blonde",
  //     "The Italian Job",
  //   ],
  //   awards: ["1 Academy Award", "1 Golden Globe"],
  //   profile: "https://www.imdb.com/name/nm0000234/",
  // },
  // {
  //   id: 22,
  //   name: "Will Smith",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Will_Smith_2019_by_Glenn_Francis.jpg",
  //   movies: ["Men in Black", "Pursuit of Happyness", "I Am Legend", "Aladdin"],
  //   awards: ["1 Academy Award", "4 Grammy Awards"],
  //   profile: "https://www.imdb.com/name/nm0000226/",
  // },
  // {
  //   id: 23,
  //   name: "Nicole Kidman",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Nicole_Kidman_Cannes_2017_4_%28cropped%29.jpg",
  //   movies: ["Moulin Rouge!", "The Others", "The Hours", "Big Little Lies"],
  //   awards: ["1 Academy Award", "5 Golden Globes"],
  //   profile: "https://www.imdb.com/name/nm0000173/",
  // },
  // {
  //   id: 24,
  //   name: "Samuel L. Jackson",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/0/03/Samuel_L_Jackson_2019_by_Glenn_Francis.jpg",
  //   movies: ["Pulp Fiction", "The Avengers", "Django Unchained", "Unbreakable"],
  //   awards: ["1 Academy Award", "BAFTA Award"],
  //   profile: "https://www.imdb.com/name/nm0000168/",
  // },
  // {
  //   id: 25,
  //   name: "Chris Hemsworth",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Chris_Hemsworth_by_Gage_Skidmore_2.jpg",
  //   movies: ["Thor", "The Avengers", "Extraction", "Rush"],
  //   awards: ["People's Choice Award", "MTV Movie Award"],
  //   profile: "https://www.imdb.com/name/nm1165110/",
  // },
  // {
  //   id: 26,
  //   name: "Daniel Craig",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Daniel_Craig_2015.jpg",
  //   movies: [
  //     "James Bond Series",
  //     "Knives Out",
  //     "Layer Cake",
  //     "The Girl with the Dragon Tattoo",
  //   ],
  //   awards: ["1 BAFTA Nomination", "Golden Globe Nomination"],
  //   profile: "https://www.imdb.com/name/nm0185819/",
  // },
  // {
  //   id: 27,
  //   name: "Gal Gadot",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Gal_Gadot_by_Gage_Skidmore_2.jpg",
  //   movies: ["Wonder Woman", "Justice League", "Fast & Furious", "Red Notice"],
  //   awards: ["MTV Movie Award", "Teen Choice Award"],
  //   profile: "https://www.imdb.com/name/nm2933757/",
  // },
  // {
  //   id: 28,
  //   name: "Joaquin Phoenix",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/3/34/Joaquin_Phoenix_at_the_2018_Berlin_Film_Festival_%28cropped%29.jpg",
  //   movies: ["Joker", "Gladiator", "Walk the Line", "Her"],
  //   awards: ["1 Academy Award", "2 Golden Globes"],
  //   profile: "https://www.imdb.com/name/nm0001618/",
  // },
  // {
  //   id: 29,
  //   name: "Reese Witherspoon",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/7/75/Reese_Witherspoon_at_the_2012_TIFF_%28cropped%29.jpg",
  //   movies: ["Legally Blonde", "Wild", "Walk the Line", "Big Little Lies"],
  //   awards: ["1 Academy Award", "2 Golden Globes"],
  //   profile: "https://www.imdb.com/name/nm0000702/",
  // },
  // {
  //   id: 30,
  //   name: "Matthew McConaughey",
  //   img: "https://upload.wikimedia.org/wikipedia/commons/2/21/Matthew_McConaughey_-_Goldene_Kamera_2014_-_Berlin.jpg",
  //   movies: [
  //     "Dallas Buyers Club",
  //     "Interstellar",
  //     "True Detective",
  //     "The Wolf of Wall Street",
  //   ],
  //   awards: ["1 Academy Award", "2 Golden Globes"],
  //   profile: "https://www.imdb.com/name/nm0000190/",
  // },
];